# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WheatherTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WheatherTest

   pod 'SwiftyJSON', '~> 4.0'
   pod 'SnapKit', '~> 4.0.0'
   #pod 'RealmSwift', '~> 3.1.1'
   pod 'Moya', '~> 11.0', '~> 11.0.1'

end
